management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'

spring:
  redis:
    port: 6379
    host: centos1


---
# redisson 会优先加载
spring:
  config:
    activate:
      on-profile: redisson
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://172.16.1.104:6379