management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'

spring:
  redis:
    port: 6379
    host: centos1


---
# redisson 会优先加载
spring:
  profiles: redisson

  redis:
    redisson:
      config: |
        sentinelServersConfig:
          checkSentinelsList: false
          masterName: mymaster
          sentinelAddresses:
            - redis://172.16.1.104:26379
