spring:
  redis:
    port: 6379
    host: centos1

    redisson:
      file: classpath:redisson-single-redis.yaml

management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
