server:
  port: 8986

spring:
  application:
    name: api-demo


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



security:
  oauth2:
    client:
      client-id: xxx
      client-secret: secret
      access-token-uri: http://127.0.0.1:7777/oauth/token
      user-authorization-uri: http://127.0.0.1:7777/oauth/authorize
    resource:
      jwt:
#        key-uri: http://127.0.0.1:7777/oauth/token_key
        key-uri: http://127.0.0.1:7777/.well-known/jwks

