server:
  port: 8986
  servlet:
    session:
      cookie:
        name: OAUTH2CLIENTSESSION
spring:
  application:
    name: api-demo


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



security:
  oauth2:
    client:
      client-id: xxx
      client-secret: secret
      access-token-uri: http://127.0.0.1:7777/oauth/token
      user-authorization-uri: http://127.0.0.1:7777/oauth/authorize
      scope: api
    #      clientAuthenticationScheme: form
    resource:
      jwt:
        key-uri: http://127.0.0.1:7777/oauth/token_key

---
spring:
  profiles: client1

server:
  port: 7788

---
spring:
  profiles: client2
server:
  port: 8986
