server:
  port: 7777

spring:
  application:
    name: auth-demo
  thymeleaf:
    prefix: classpath:/templates/ # 不加，使用默认配置也行
    suffix: .html # 不加，使用默认配置也行
    encoding: UTF-8
    cache: false # 开发环境关闭缓存


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: '*'

#logging:
#  level:
#    root: debug