server:
  port: 10001

spring:
  application:
    name: feign-demo


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1