server:
  port: 7777

spring:
  application:
    name: auth-demo


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'