// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressBook.proto

package com.ooooo.protobuf;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:experimental_code.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .experimental_code.Person person = 1;</code>
   */
  java.util.List<com.ooooo.protobuf.Person> 
      getPersonList();
  /**
   * <code>repeated .experimental_code.Person person = 1;</code>
   */
  com.ooooo.protobuf.Person getPerson(int index);
  /**
   * <code>repeated .experimental_code.Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .experimental_code.Person person = 1;</code>
   */
  java.util.List<? extends com.ooooo.protobuf.PersonOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .experimental_code.Person person = 1;</code>
   */
  com.ooooo.protobuf.PersonOrBuilder getPersonOrBuilder(
      int index);
}
