// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressBook.proto

package com.ooooo.protobuf;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_experimental_code_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_experimental_code_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_experimental_code_Person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_experimental_code_Person_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_experimental_code_AddressBook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_experimental_code_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021AddressBook.proto\022\021experimental_code\"\263" +
      "\002\n\006Person\022\021\n\004name\030\001 \001(\tH\000\210\001\001\022\017\n\002id\030\002 \001(\005" +
      "H\001\210\001\001\022\022\n\005email\030\003 \001(\tH\002\210\001\001\022:\n\013phoneNumber" +
      "\030\004 \003(\0132%.experimental_code.Person.PhoneN" +
      "umber\032n\n\013PhoneNumber\022\023\n\006number\030\001 \001(\tH\000\210\001" +
      "\001\0226\n\004type\030\002 \001(\0162#.experimental_code.Pers" +
      "on.PhoneTypeH\001\210\001\001B\t\n\007_numberB\007\n\005_type\"+\n" +
      "\tPhoneType\022\n\n\006mobile\020\000\022\010\n\004home\020\001\022\010\n\004work" +
      "\020\002B\007\n\005_nameB\005\n\003_idB\010\n\006_email\"8\n\013AddressB" +
      "ook\022)\n\006person\030\001 \003(\0132\031.experimental_code." +
      "PersonB)\n\022com.ooooo.protobufB\021AddressBoo" +
      "kProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_experimental_code_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_experimental_code_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_experimental_code_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "PhoneNumber", "Name", "Id", "Email", });
    internal_static_experimental_code_Person_PhoneNumber_descriptor =
      internal_static_experimental_code_Person_descriptor.getNestedTypes().get(0);
    internal_static_experimental_code_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_experimental_code_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", "Number", "Type", });
    internal_static_experimental_code_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_experimental_code_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_experimental_code_AddressBook_descriptor,
        new java.lang.String[] { "Person", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
