// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressBook.proto

package com.ooooo.protobuf;

/**
 * Protobuf type {@code experimental_code.Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:experimental_code.Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    name_ = "";
    email_ = "";
    phoneNumber_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            name_ = s;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            id_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            email_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              phoneNumber_ = new java.util.ArrayList<com.ooooo.protobuf.Person.PhoneNumber>();
              mutable_bitField0_ |= 0x00000008;
            }
            phoneNumber_.add(
                input.readMessage(com.ooooo.protobuf.Person.PhoneNumber.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        phoneNumber_ = java.util.Collections.unmodifiableList(phoneNumber_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ooooo.protobuf.AddressBookProtos.internal_static_experimental_code_Person_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.ooooo.protobuf.AddressBookProtos.internal_static_experimental_code_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.ooooo.protobuf.Person.class, com.ooooo.protobuf.Person.Builder.class);
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.ooooo.protobuf.Person)) {
      return super.equals(obj);
    }
    com.ooooo.protobuf.Person other = (com.ooooo.protobuf.Person) obj;

    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
              .equals(other.getName())) return false;
    }
    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
              != other.getId()) return false;
    }
    if (hasEmail() != other.hasEmail()) return false;
    if (hasEmail()) {
      if (!getEmail()
              .equals(other.getEmail())) return false;
    }
    if (!getPhoneNumberList()
            .equals(other.getPhoneNumberList())) return false;
    return unknownFields.equals(other.unknownFields);
  }

  public interface PhoneNumberOrBuilder extends
          // @@protoc_insertion_point(interface_extends:experimental_code.Person.PhoneNumber)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string number = 1;</code>
     *
     * @return Whether the number field is set.
     */
    boolean hasNumber();

    /**
     * <code>optional string number = 1;</code>
     *
     * @return The number.
     */
    java.lang.String getNumber();

    /**
     * <code>optional string number = 1;</code>
     *
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
    getNumberBytes();

    /**
     * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
     *
     * @return Whether the type field is set.
     */
    boolean hasType();

    /**
     * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
     *
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();

    /**
     * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
     *
     * @return The type.
     */
    com.ooooo.protobuf.Person.PhoneType getType();
  }

  /**
   * Protobuf enum {@code experimental_code.Person.PhoneType}
   */
  public enum PhoneType
          implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>mobile = 0;</code>
     */
    mobile(0),
    /**
     * <code>home = 1;</code>
     */
    home(1),
    /**
     * <code>work = 2;</code>
     */
    work(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>mobile = 0;</code>
     */
    public static final int mobile_VALUE = 0;
    /**
     * <code>home = 1;</code>
     */
    public static final int home_VALUE = 1;
    /**
     * <code>work = 2;</code>
     */
    public static final int work_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PhoneType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PhoneType forNumber(int value) {
      switch (value) {
        case 0: return mobile;
        case 1: return home;
        case 2: return work;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PhoneType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
            public PhoneType findValueByNumber(int number) {
              return PhoneType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ooooo.protobuf.Person.getDescriptor().getEnumTypes().get(0);
    }

    private static final PhoneType[] VALUES = values();

    public static PhoneType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    PhoneType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:experimental_code.Person.PhoneType)
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;

  /**
   * <code>optional string name = 1;</code>
   *
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>optional string name = 1;</code>
   *
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }

  /**
   * <code>optional string name = 1;</code>
   *
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_;

  /**
   * <code>optional int32 id = 2;</code>
   *
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000002) != 0);
  }

  /**
   * <code>optional int32 id = 2;</code>
   *
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object email_;

  /**
   * <code>optional string email = 3;</code>
   *
   * @return Whether the email field is set.
   */
  @java.lang.Override
  public boolean hasEmail() {
    return ((bitField0_ & 0x00000004) != 0);
  }

  /**
   * <code>optional string email = 3;</code>
   *
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }

  /**
   * <code>optional string email = 3;</code>
   *
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONENUMBER_FIELD_NUMBER = 4;
  private java.util.List<com.ooooo.protobuf.Person.PhoneNumber> phoneNumber_;

  /**
   * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.ooooo.protobuf.Person.PhoneNumber> getPhoneNumberList() {
    return phoneNumber_;
  }

  /**
   * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ooooo.protobuf.Person.PhoneNumberOrBuilder>
  getPhoneNumberOrBuilderList() {
    return phoneNumber_;
  }

  /**
   * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
   */
  @java.lang.Override
  public int getPhoneNumberCount() {
    return phoneNumber_.size();
  }

  /**
   * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
   */
  @java.lang.Override
  public com.ooooo.protobuf.Person.PhoneNumber getPhoneNumber(int index) {
    return phoneNumber_.get(index);
  }

  /**
   * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
   */
  @java.lang.Override
  public com.ooooo.protobuf.Person.PhoneNumberOrBuilder getPhoneNumberOrBuilder(
          int index) {
    return phoneNumber_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, id_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    for (int i = 0; i < phoneNumber_.size(); i++) {
      output.writeMessage(4, phoneNumber_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(2, id_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    for (int i = 0; i < phoneNumber_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(4, phoneNumber_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  /**
   * Protobuf type {@code experimental_code.Person.PhoneNumber}
   */
  public static final class PhoneNumber extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:experimental_code.Person.PhoneNumber)
          PhoneNumberOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneNumber() {
      number_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PhoneNumber();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneNumber(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              number_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              bitField0_ |= 0x00000002;
              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ooooo.protobuf.AddressBookProtos.internal_static_experimental_code_Person_PhoneNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ooooo.protobuf.AddressBookProtos.internal_static_experimental_code_Person_PhoneNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ooooo.protobuf.Person.PhoneNumber.class, com.ooooo.protobuf.Person.PhoneNumber.Builder.class);
    }

    private int bitField0_;
    public static final int NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object number_;
    /**
     * <code>optional string number = 1;</code>
     * @return Whether the number field is set.
     */
    @java.lang.Override
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>optional string number = 1;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public com.ooooo.protobuf.Person.PhoneType getType() {
      @SuppressWarnings("deprecation")
      com.ooooo.protobuf.Person.PhoneType result = com.ooooo.protobuf.Person.PhoneType.valueOf(type_);
      return result == null ? com.ooooo.protobuf.Person.PhoneType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ooooo.protobuf.Person.PhoneNumber)) {
        return super.equals(obj);
      }
      com.ooooo.protobuf.Person.PhoneNumber other = (com.ooooo.protobuf.Person.PhoneNumber) obj;

      if (hasNumber() != other.hasNumber()) return false;
      if (hasNumber()) {
        if (!getNumber()
            .equals(other.getNumber())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNumber()) {
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ooooo.protobuf.Person.PhoneNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ooooo.protobuf.Person.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ooooo.protobuf.Person.PhoneNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code experimental_code.Person.PhoneNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:experimental_code.Person.PhoneNumber)
        com.ooooo.protobuf.Person.PhoneNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ooooo.protobuf.AddressBookProtos.internal_static_experimental_code_Person_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ooooo.protobuf.AddressBookProtos.internal_static_experimental_code_Person_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ooooo.protobuf.Person.PhoneNumber.class, com.ooooo.protobuf.Person.PhoneNumber.Builder.class);
      }

      // Construct using com.ooooo.protobuf.Person.PhoneNumber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ooooo.protobuf.AddressBookProtos.internal_static_experimental_code_Person_PhoneNumber_descriptor;
      }

      @java.lang.Override
      public com.ooooo.protobuf.Person.PhoneNumber getDefaultInstanceForType() {
        return com.ooooo.protobuf.Person.PhoneNumber.getDefaultInstance();
      }

      @java.lang.Override
      public com.ooooo.protobuf.Person.PhoneNumber build() {
        com.ooooo.protobuf.Person.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ooooo.protobuf.Person.PhoneNumber buildPartial() {
        com.ooooo.protobuf.Person.PhoneNumber result = new com.ooooo.protobuf.Person.PhoneNumber(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ooooo.protobuf.Person.PhoneNumber) {
          return mergeFrom((com.ooooo.protobuf.Person.PhoneNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ooooo.protobuf.Person.PhoneNumber other) {
        if (other == com.ooooo.protobuf.Person.PhoneNumber.getDefaultInstance()) return this;
        if (other.hasNumber()) {
          bitField0_ |= 0x00000001;
          number_ = other.number_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ooooo.protobuf.Person.PhoneNumber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ooooo.protobuf.Person.PhoneNumber) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object number_ = "";
      /**
       * <code>optional string number = 1;</code>
       * @return Whether the number field is set.
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string number = 1;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        number_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.ooooo.protobuf.Person.PhoneType getType() {
        @SuppressWarnings("deprecation")
        com.ooooo.protobuf.Person.PhoneType result = com.ooooo.protobuf.Person.PhoneType.valueOf(type_);
        return result == null ? com.ooooo.protobuf.Person.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.ooooo.protobuf.Person.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .experimental_code.Person.PhoneType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:experimental_code.Person.PhoneNumber)
    }

    // @@protoc_insertion_point(class_scope:experimental_code.Person.PhoneNumber)
    private static final com.ooooo.protobuf.Person.PhoneNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ooooo.protobuf.Person.PhoneNumber();
    }

    public static com.ooooo.protobuf.Person.PhoneNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneNumber>
        PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
      @java.lang.Override
      public PhoneNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneNumber(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PhoneNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ooooo.protobuf.Person.PhoneNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (hasEmail()) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
    }
    if (getPhoneNumberCount() > 0) {
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumberList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ooooo.protobuf.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ooooo.protobuf.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ooooo.protobuf.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ooooo.protobuf.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ooooo.protobuf.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ooooo.protobuf.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ooooo.protobuf.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ooooo.protobuf.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ooooo.protobuf.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ooooo.protobuf.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ooooo.protobuf.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ooooo.protobuf.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ooooo.protobuf.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code experimental_code.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:experimental_code.Person)
      com.ooooo.protobuf.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ooooo.protobuf.AddressBookProtos.internal_static_experimental_code_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ooooo.protobuf.AddressBookProtos.internal_static_experimental_code_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ooooo.protobuf.Person.class, com.ooooo.protobuf.Person.Builder.class);
    }

    // Construct using com.ooooo.protobuf.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPhoneNumberFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      email_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      if (phoneNumberBuilder_ == null) {
        phoneNumber_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        phoneNumberBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ooooo.protobuf.AddressBookProtos.internal_static_experimental_code_Person_descriptor;
    }

    @java.lang.Override
    public com.ooooo.protobuf.Person getDefaultInstanceForType() {
      return com.ooooo.protobuf.Person.getDefaultInstance();
    }

    @java.lang.Override
    public com.ooooo.protobuf.Person build() {
      com.ooooo.protobuf.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ooooo.protobuf.Person buildPartial() {
      com.ooooo.protobuf.Person result = new com.ooooo.protobuf.Person(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.email_ = email_;
      if (phoneNumberBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          phoneNumber_ = java.util.Collections.unmodifiableList(phoneNumber_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.phoneNumber_ = phoneNumber_;
      } else {
        result.phoneNumber_ = phoneNumberBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ooooo.protobuf.Person) {
        return mergeFrom((com.ooooo.protobuf.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ooooo.protobuf.Person other) {
      if (other == com.ooooo.protobuf.Person.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasEmail()) {
        bitField0_ |= 0x00000004;
        email_ = other.email_;
        onChanged();
      }
      if (phoneNumberBuilder_ == null) {
        if (!other.phoneNumber_.isEmpty()) {
          if (phoneNumber_.isEmpty()) {
            phoneNumber_ = other.phoneNumber_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePhoneNumberIsMutable();
            phoneNumber_.addAll(other.phoneNumber_);
          }
          onChanged();
        }
      } else {
        if (!other.phoneNumber_.isEmpty()) {
          if (phoneNumberBuilder_.isEmpty()) {
            phoneNumberBuilder_.dispose();
            phoneNumberBuilder_ = null;
            phoneNumber_ = other.phoneNumber_;
            bitField0_ = (bitField0_ & ~0x00000008);
            phoneNumberBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhoneNumberFieldBuilder() : null;
          } else {
            phoneNumberBuilder_.addAllMessages(other.phoneNumber_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ooooo.protobuf.Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ooooo.protobuf.Person) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>optional int32 id = 2;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000002;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>optional string email = 3;</code>
     * @return Whether the email field is set.
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      bitField0_ = (bitField0_ & ~0x00000004);
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 3;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      email_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.ooooo.protobuf.Person.PhoneNumber> phoneNumber_ =
      java.util.Collections.emptyList();
    private void ensurePhoneNumberIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        phoneNumber_ = new java.util.ArrayList<com.ooooo.protobuf.Person.PhoneNumber>(phoneNumber_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ooooo.protobuf.Person.PhoneNumber, com.ooooo.protobuf.Person.PhoneNumber.Builder, com.ooooo.protobuf.Person.PhoneNumberOrBuilder> phoneNumberBuilder_;

    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public java.util.List<com.ooooo.protobuf.Person.PhoneNumber> getPhoneNumberList() {
      if (phoneNumberBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phoneNumber_);
      } else {
        return phoneNumberBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public int getPhoneNumberCount() {
      if (phoneNumberBuilder_ == null) {
        return phoneNumber_.size();
      } else {
        return phoneNumberBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public com.ooooo.protobuf.Person.PhoneNumber getPhoneNumber(int index) {
      if (phoneNumberBuilder_ == null) {
        return phoneNumber_.get(index);
      } else {
        return phoneNumberBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public Builder setPhoneNumber(
        int index, com.ooooo.protobuf.Person.PhoneNumber value) {
      if (phoneNumberBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumberIsMutable();
        phoneNumber_.set(index, value);
        onChanged();
      } else {
        phoneNumberBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public Builder setPhoneNumber(
        int index, com.ooooo.protobuf.Person.PhoneNumber.Builder builderForValue) {
      if (phoneNumberBuilder_ == null) {
        ensurePhoneNumberIsMutable();
        phoneNumber_.set(index, builderForValue.build());
        onChanged();
      } else {
        phoneNumberBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public Builder addPhoneNumber(com.ooooo.protobuf.Person.PhoneNumber value) {
      if (phoneNumberBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumberIsMutable();
        phoneNumber_.add(value);
        onChanged();
      } else {
        phoneNumberBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public Builder addPhoneNumber(
        int index, com.ooooo.protobuf.Person.PhoneNumber value) {
      if (phoneNumberBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumberIsMutable();
        phoneNumber_.add(index, value);
        onChanged();
      } else {
        phoneNumberBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public Builder addPhoneNumber(
        com.ooooo.protobuf.Person.PhoneNumber.Builder builderForValue) {
      if (phoneNumberBuilder_ == null) {
        ensurePhoneNumberIsMutable();
        phoneNumber_.add(builderForValue.build());
        onChanged();
      } else {
        phoneNumberBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public Builder addPhoneNumber(
        int index, com.ooooo.protobuf.Person.PhoneNumber.Builder builderForValue) {
      if (phoneNumberBuilder_ == null) {
        ensurePhoneNumberIsMutable();
        phoneNumber_.add(index, builderForValue.build());
        onChanged();
      } else {
        phoneNumberBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public Builder addAllPhoneNumber(
        java.lang.Iterable<? extends com.ooooo.protobuf.Person.PhoneNumber> values) {
      if (phoneNumberBuilder_ == null) {
        ensurePhoneNumberIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phoneNumber_);
        onChanged();
      } else {
        phoneNumberBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public Builder clearPhoneNumber() {
      if (phoneNumberBuilder_ == null) {
        phoneNumber_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        phoneNumberBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public Builder removePhoneNumber(int index) {
      if (phoneNumberBuilder_ == null) {
        ensurePhoneNumberIsMutable();
        phoneNumber_.remove(index);
        onChanged();
      } else {
        phoneNumberBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public com.ooooo.protobuf.Person.PhoneNumber.Builder getPhoneNumberBuilder(
        int index) {
      return getPhoneNumberFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public com.ooooo.protobuf.Person.PhoneNumberOrBuilder getPhoneNumberOrBuilder(
        int index) {
      if (phoneNumberBuilder_ == null) {
        return phoneNumber_.get(index);  } else {
        return phoneNumberBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public java.util.List<? extends com.ooooo.protobuf.Person.PhoneNumberOrBuilder> 
         getPhoneNumberOrBuilderList() {
      if (phoneNumberBuilder_ != null) {
        return phoneNumberBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phoneNumber_);
      }
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public com.ooooo.protobuf.Person.PhoneNumber.Builder addPhoneNumberBuilder() {
      return getPhoneNumberFieldBuilder().addBuilder(
          com.ooooo.protobuf.Person.PhoneNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public com.ooooo.protobuf.Person.PhoneNumber.Builder addPhoneNumberBuilder(
        int index) {
      return getPhoneNumberFieldBuilder().addBuilder(
          index, com.ooooo.protobuf.Person.PhoneNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .experimental_code.Person.PhoneNumber phoneNumber = 4;</code>
     */
    public java.util.List<com.ooooo.protobuf.Person.PhoneNumber.Builder> 
         getPhoneNumberBuilderList() {
      return getPhoneNumberFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ooooo.protobuf.Person.PhoneNumber, com.ooooo.protobuf.Person.PhoneNumber.Builder, com.ooooo.protobuf.Person.PhoneNumberOrBuilder> 
        getPhoneNumberFieldBuilder() {
      if (phoneNumberBuilder_ == null) {
        phoneNumberBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ooooo.protobuf.Person.PhoneNumber, com.ooooo.protobuf.Person.PhoneNumber.Builder, com.ooooo.protobuf.Person.PhoneNumberOrBuilder>(
                phoneNumber_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        phoneNumber_ = null;
      }
      return phoneNumberBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:experimental_code.Person)
  }

  // @@protoc_insertion_point(class_scope:experimental_code.Person)
  private static final com.ooooo.protobuf.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ooooo.protobuf.Person();
  }

  public static com.ooooo.protobuf.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Person(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ooooo.protobuf.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

