server:
  port: 8986
  servlet:
    session:
      cookie:
        name: OAUTH2CLIENTSESSION
spring:
  application:
    name: demo-spring-cloud-authorize-client


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1

security:
  oauth2:
    client:
      client-id: xxx
      client-secret: secret
      access-token-uri: http://127.0.0.1:8888/auth/oauth/token
      user-authorization-uri: http://127.0.0.1:8888/auth/oauth/authorize
      scope: api
    #      clientAuthenticationScheme: form
    resource:
      jwt:
        key-uri: http://127.0.0.1:8888/auth/oauth/token_key

---
spring:
  profiles: client1

server:
  port: 7788

---
spring:
  profiles: client2
server:
  port: 8986
